### PR TITLE
Re-order plot sections to match usage

### LINKED ISSUE #3: Change default layout of website
Typical use has given us an idea of what the default layout should. More important blocks should go higher up, logged values that have little variation don't need to be plotted, etc.

### PR DESCRIPTION
**Pull request by pbitzer**
Reorder the layout of the sensor pages

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
This PR is targeting `v0.2.x` as it should, but the changes were based on `master`, leading to the commits and diffs being all borked. To fix this, in your branch, run the following command:

```bash
git rebase --onto v0.2.x master new_layout
```

And make sure to fix any merge conflicts (there shouldn't be any, AFAIK).

**Review by CAM-Gerlach — COMMENTED** [review]
Other than the Git borkage which needs to be fixed, LGTM

**Comment by pbitzer** [comment]
> This PR is targeting `v0.2.x` as it should, but the changes were based on `master`, leading to the commits and diffs being all borked. To fix this, in your branch, run the following command:
> 
> ```shell
> git rebase --onto v0.2.x master new_layout
> ```
> 
> And make sure to fix any merge conflicts (there shouldn't be any, AFAIK).

Alright, should be good to go now!

**Comment by CAM-Gerlach** [comment]
Unfortunately looks like it did a weird merge of some sort instead. I'll take a crack at fixing it myself, hold on (same caveats as #12 apply if you want to re-pull the fixed commits).

**Comment by CAM-Gerlach** [comment]
@pbitzer Huh, I dropped the spurious merge comment and then re-ran the exact command above on your branch and it worked exactly as expected, so I'm not sure what went wrong. Good 'ole git, I guess...looks good now.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @pbitzer !

**Pull request merged**
